Add name prop to fields containers divs
coopiteasy/vertical-cooperative pull request #165
Opened 2021-06-16 15:24 UTC by cesarlr

hi @robinkeunen we have added name property to container divs for make inheritance easier

2021-06-28 09:10 UTC, cesarlr commented
@remytms @robinkeunen What about this?

2021-06-28 09:16 UTC, robinkeunen requested changes
Hi @cesarlr thanks for that long awaited dev request ;-)

Minor things to change for the csrf divs.

2021-06-28 09:16 UTC, robinkeunen commented on easy_my_coop_website/views/subscription_template.xml
> +                                    </p>
This banner is used to display error message that may be unrelated to csrf tokens. It should be out of the csrf div.

2021-06-28 09:16 UTC, robinkeunen commented on easy_my_coop_website/views/subscription_template.xml
> +                                    </p>
same here.

2021-06-29 06:46 UTC, cesarlr commented
@robinkeunen Done!

2021-06-29 11:30 UTC, enricostano approved these changes

2021-06-29 13:19 UTC, robinkeunen approved these changes

2021-06-29 15:23 UTC, remytms approved these changes
:heart:

2021-06-29 16:15 UTC, merged