Dupliquer un contact coop avec les champs "coopérateur" et "member" décoché par défaut
coopiteasy/vertical-cooperative pull request #176
Opened 2021-10-26 15:15 UTC by coccinouille

L'option copy=False est ajouté pour les trois champs, dans models.
De cette manière le champs cooperator_register_number n'est pas affiché lorsqu'on duplique un contact. 

https://gestion.coopiteasy.be/web#id=5425&view_type=form&model=project.task

@robinkeunen @huguesdk @remytms

2021-10-26 15:20 UTC, robinkeunen requested changes
Good job on your first PR! By installing pre-commit, you'll be able to catch some linting problems.

2021-10-26 15:20 UTC, robinkeunen commented on easy_my_coop/models/partner.py
> +    cooperator_register_number = fields.Integer(string="Cooperator Number", copy=False)
This line is too long, pre-commit would fix this :-)

2021-10-26 15:25 UTC, robinkeunen approved these changes
nevermind, my bad.

congrats 🎉 

Did you link this PR in the field _PR URL_ of the task?

It is also better to link the task in the PR description as well (next time) :-)

2021-10-27 09:09 UTC, victor-champonnois commented
> Did you link this PR in the field _PR URL_ of the task?

Done

> 
> It is also better to link the task in the PR description as well (next time) :-)

Noted :)

2021-11-04 15:23 UTC, enricostano commented
Nice! :+1:

2021-12-10 16:36 UTC, merged