easy_my_coop: Set mail.template.easy_my_coop field to True on migration
coopiteasy/vertical-cooperative pull request #185
Opened 2021-11-26 08:46 UTC by carmenbianca

Previously, for some reason, these did not default to True, or somehow
lost their truthiness during migration from v8 to v12. Whatever the
case, this should make sure that doesn't happen.

T2772

2021-11-29 10:35 UTC, remytms reviewed
Hi @carmenbianca,
Thanks for this work.

First of all, as your migration script uses `openugradelib`, it should go on a dedicated branch named `12.0-openupgrade`. As we don't want `openupgradelib` as a dependencies to our module except when we are migrating databases.

My second point is that, I think `post-migration.py` can be used instead of `end-migration.py` because I don't think that we need to wait the end of the update of all module to do this fix. It can be done just after the update of this module.

What do you think about that ?

2021-11-30 07:28 UTC, carmenbianca commented
Hi @remytms 

1. Would it have been possible to use a different library instead? Is it preferable to write using a different library?
2. I chose `end-migration.py` because other modules in vertical-cooperative also create `easy_my_coop%` templates. My logic was to let all vertical-cooperative modules do their upgrading, and then finally apply this migration script to all of them. I would have preferred to instead have a migration script for every individual module that creates/owns `easy_my_coop%` templates, but I don't know how to write a script that _only_ affects the rows belonging to a module.

2022-01-11 17:01 UTC, robinkeunen commented
I'm doing a bit of cleanup:

> 1. Would it have been possible to use a different library instead? Is it preferable to write using a different library?

You can do it without the openupgrade library, it's just a bit more verbose, something like:

```py
def migrate(cr, version):
    with api.Environment.manage():
        env = api.Environment(cr, SUPERUSER_ID, {})
        holidays_without_meeting = env['hr.holidays.public.line'].search([
            ('meeting_id', '=', False)])
        for holiday in holidays_without_meeting:
            _logger.debug('Creating meeting for holiday: %s' % holiday.name)
            holiday.meeting_id = env['calendar.event'].create(
                holiday._prepare_holidays_meeting_values())
```

I'm leaving the second question to @remytms

2022-01-31 09:43 UTC, carmenbianca commented
Also doing cleanup :) Pinging @remytms

2022-02-21 16:26 UTC, robinkeunen commented
@remytms since you're in migration stuff, now is the good time :D

2022-03-03 10:49 UTC, huguesdk commented
unfortunately, the script currently fails with this error:
```
Traceback (most recent call last):
  File "/home/mig/coopiteasy/env/modoo12/openupgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/mig/coopiteasy/env/modoo12/openupgrade/odoo/modules/loading.py", line 505, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/mig/coopiteasy/env/modoo12/openupgrade/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/mig/coopiteasy/env/modoo12/venv/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1892, in wrapped_function
    if use_env2 else cr, version)
  File "/home/mig/coopiteasy/env/modoo12/coopiteasy/vertical-cooperative/easy_my_coop/migrations/12.0.1.0.0/end-migration.py", line 15, in migrate
    if not entry.easy_my_coop:
AttributeError: 'ir.model.data' object has no attribute 'easy_my_coop'
```
but it might be a configuration problem on my side. i’ll check tomorrow.

2022-03-04 10:30 UTC, carmenbianca commented
@huguesdk That error seems correct. It should have a `mail.template` object, not a `ir.model.data` object.

2022-03-07 08:54 UTC, carmenbianca commented
Alternatively: Make `easy_my_coop` a computed value that checks whether module of the template starts with `easy_my_coop%`. No migration script needed.

2022-03-07 15:56 UTC, huguesdk requested changes
testing this code without doing a migration is a little tricky, although if `openupgradelib` is available, you could maybe import this module in an odoo shell and call the `migrate()` function.

if it doesn’t work, simply testing the function by copy-pasting it (without the decorator) in an odoo shell would do. it should work on a database in version 12.

why the 12.0.1.0.0 as version and not the latest one (1.0.3.2.0)? is it because it is the version where the `mail.template.easy_my_coop` property was added?

2022-03-07 15:56 UTC, huguesdk commented on easy_my_coop/migrations/12.0.1.0.0/end-migration.py
> +    templates = env["ir.model.data"].search(domain)
```suggestion
    model_data = env["ir.model.data"].search(domain)
    templates = env["mail.template"].browse([md.res_id for md in model_data])
```

2022-03-07 15:56 UTC, huguesdk commented on easy_my_coop/migrations/12.0.1.0.0/end-migration.py
> +                    "{}.{}".format(entry.module, entry.name)
`entry` should be a `mail.template` object, which has no `.module` property.

2022-05-13 14:37 UTC, huguesdk commented
i’ve just fixed the script and changed the base of this pr to `12.0-openupgrade`, which i also rebased on the latest release. i’ve tested the result and it works as expected.

2022-05-13 14:38 UTC, huguesdk approved these changes

2022-05-13 14:42 UTC, merged