12.0 replace partner age
coopiteasy/vertical-cooperative pull request #223
Opened 2022-03-02 14:42 UTC by coccinouille

[related issue](https://github.com/coopiteasy/vertical-cooperative/issues/219)

2022-03-02 15:42 UTC, robinkeunen requested changes
You can't remove this module because beesdoo_easy_my_coop also depends on it. We can only remove the dependency here because we do not use introduced `age` field in this module.

2022-03-03 08:47 UTC, coccinouille commented
Noted for not removing the module.

What has been tested:
 installing on empty DB

2022-03-11 09:51 UTC, coccinouille commented
branch rebased

2022-03-11 09:56 UTC, carmenbianca approved these changes

2022-03-18 10:07 UTC, robinkeunen approved these changes

2022-03-18 10:08 UTC, merged