12.0 rename easy my coop fr
coopiteasy/vertical-cooperative pull request #229
Opened 2022-03-09 10:41 UTC by coccinouille

[related issue](https://github.com/coopiteasy/vertical-cooperative/issues/208)

2022-03-09 15:38 UTC, robinkeunen approved these changes

2022-03-16 10:46 UTC, vdewulf commented
@victor-champonnois 
Tested on https://demain.komunigi.test.coopiteasy.be/
After having added the test ribbon, 
After having set up the right API google recaptcha key on the website administration
After having found the direct link to the form to become cooperator (as there is no direct link on the website menu): https://demain.komunigi.test.coopiteasy.be/become_cooperator
I was able to test the following steps:

- Fill in the form
NOT OK : some texts are in French (Courriel + confirmer l'émail), other still in English. 
Is the PO file alright?

I filled all the fields except the Gender
The Total share is a readonly field and was not updated when I chose 2 shares.

I got a 500: Internal Server Error
When I went back, the Gender field had been set to Masculin without asking me anything.

I stop my test here because even if I fill in everything, I got this 500 internal error.

2022-03-16 10:47 UTC, vdewulf requested changes
Tested on https://demain.komunigi.test.coopiteasy.be/
After having added the test ribbon, 
After having set up the right API google recaptcha key on the website administration
After having found the direct link to the form to become cooperator (as there is no direct link on the website menu): https://demain.komunigi.test.coopiteasy.be/become_cooperator
I was able to test the following steps:

- Fill in the form
NOT OK : some texts are in French (Courriel + confirmer l'émail), other still in English. 
Is the PO file alright?

I filled all the fields except the Gender
The Total share is a readonly field and was not updated when I chose 2 shares.

I got a 500: Internal Server Error
When I went back, the Gender field had been set to Masculin without asking me anything.

I stop my test here because even if I fill in everything, I got this 500 internal error.

2022-03-17 10:49 UTC, carmenbianca commented
Rebased this on top of 12.0-komunigi and set that as the merge branch.

2022-03-18 10:21 UTC, merged