[FIX] emc: replace no_registre by national_register_number
coopiteasy/vertical-cooperative pull request #23
Opened 2019-10-11 15:27 UTC by robinkeunen

iwp_website is writing on _no_registre_ but is not defined in `easy_my_coop.subscription_request`

2019-10-11 15:40 UTC, houssine78 requested changes
The national register number has been removed for legal reason. So is not stored as it is not asked anymore.

2019-10-14 14:39 UTC, houssine78 approved these changes

2019-10-14 14:39 UTC, merged

2019-10-14 14:54 UTC, robinkeunen commented
@houssine78 Please let me merge my PR myself :-)

2019-10-14 15:04 UTC, houssine78 commented
@robinkeunen ok boy ;)