[FIX] cooperator: Do not search account 416000
coopiteasy/vertical-cooperative pull request #314
Opened 2022-04-21 08:05 UTC by carmenbianca

## Description

Fixes #251 

## Odoo task (if applicable)

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] (If a new module) Moving this to OCA has been considered.

2022-04-21 09:16 UTC, robinkeunen requested changes
Left some comments.

@vdewulf 
**before this PR**
`cooperator` fetches the cooperator account
1. on the `property_cooperator_account` configuration on the company
2. if not found fetches 416000
3. if not found raises an error

**After this PR**
`cooperator` fetches the cooperator account
1. on the `property_cooperator_account` configuration field on the company
2. if not found AND l10n_be_cooperator is installed, fetches 416000
3. if not found raises an error

My question : can we make things simpler and solely rely on the configuration ? And therefore remove the code fetching account 416000 in l10n_be_cooperator ?

2022-04-21 09:16 UTC, robinkeunen commented on cooperator/models/subscription_request.py
> +            raise UserError(_("You must set a cooperator account on you company."))
typo: you**R** company

2022-04-21 09:16 UTC, robinkeunen commented on l10n_be_cooperator/models/subscription_request.py
> +
I would make things simpler : remove this and solely rely on module configuration.

2022-04-21 09:16 UTC, robinkeunen commented on cooperator/models/subscription_request.py
> +        account = self.company_id.property_cooperator_account
Can you add a note in the readme to tell the user to configure this account ?

2022-06-07 09:57 UTC, robinkeunen commented
> Left some comments.
> 
> @vdewulf **before this PR** `cooperator` fetches the cooperator account
> 
> 1. on the `property_cooperator_account` configuration on the company
> 2. if not found fetches 416000
> 3. if not found raises an error
> 
> **After this PR** `cooperator` fetches the cooperator account
> 
> 1. on the `property_cooperator_account` configuration field on the company
> 2. if not found AND l10n_be_cooperator is installed, fetches 416000
> 3. if not found raises an error
> 
> My question : can we make things simpler and solely rely on the configuration ? And therefore remove the code fetching account 416000 in l10n_be_cooperator ?

@vdewulf Did you have a chance to look into this ?

2022-06-08 12:11 UTC, vdewulf commented
@robinkeunen sorry, I tought I asnwered that.
As this field (account cooperator) is mandatory in the company config (correct me if I'm wrong), I think it's sufficient to just fetch it there, indeed.

2022-06-09 14:01 UTC, robinkeunen approved these changes

2022-06-09 14:04 UTC, robinkeunen approved these changes

2022-06-09 14:05 UTC, robinkeunen commented
/ocabot merge minor

2022-06-09 14:32 UTC, robinkeunen commented
/ocabot merge minor

2022-06-16 08:39 UTC, robinkeunen commented
/ocabot merge minor

2022-06-16 09:13 UTC, merged