12.0 backport translation updates
coopiteasy/vertical-cooperative pull request #369
Opened 2022-09-02 13:28 UTC by victor-champonnois

fix https://github.com/coopiteasy/vertical-cooperative/issues/353

2022-09-05 12:28 UTC, victor-champonnois commented
@huguesdk pour info :)

2022-09-05 14:38 UTC, robinkeunen requested changes
I think it's a bit dangerous to just copy-paste translations from versions to versions.

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +"Project-Id-Version: Odoo Server 14.0\n"
Still 12.0 ?

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +msgid ""
The invoice reference field is still `number` in 12.0

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +"    <p>Thank you for trusting ${object.env.company.name or 'us'}!</p>\n"
This may work but I see no occurrences of this in Odoo codebase

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +"    <p>Thank you for trusting ${object.env.company.name or 'us'}!</p>\n"
=> in a lot of other lower instances

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +#: code:addons/cooperator/models/subscription_request.py:0
Still at line 69 in odoo 12.

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +#: code:addons/cooperator/models/subscription_request.py:0
same here.

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +"<span groups=\"account.group_show_line_subtotals_tax_excluded\">\n"
This looks strange.

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +#: code:addons/cooperator/wizard/create_subscription_from_partner.py:0
same here

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +#: model:ir.actions.act_window,name:cooperator.action_move_out_invoice_type
Still account_invoice_action

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +#: model_terms:ir.actions.act_window,help:cooperator.action_move_out_invoice_type
idem

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +#: code:addons/cooperator/wizard/update_share_line.py:0
idem

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +msgid "Force minimum quantity?"
Need a space before ?

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/cooperator.pot
> +msgid "Is company?"
idem

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/fr.po
> +"Project-Id-Version: Odoo Server 14.0\n"
idem

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/fr.po
> +"                ${(object.name or '').replace('/','_')}_${object.state == 'draft' and 'draft' or ''}\n"
idem

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/fr.po
> +"    % if object.env.company.street:\n"
I'd be careful with these `object.env.company` as well.

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/fr.po
> +#: model:mail.template,body_html:cooperator.email_template_confirmation
Probably still `email_template_confirmation_company`

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/fr.po
> +"                Capital (Ref ${object.name or 'n/a'})\n"
idem

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/fr.po
> +#: model:ir.actions.act_window,name:cooperator.action_move_out_invoice_type
idem.

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/fr.po
> +#: model_terms:ir.actions.act_window,help:cooperator.action_move_out_invoice_type
idem

2022-09-05 14:38 UTC, robinkeunen commented on cooperator/i18n/fr.po
> +#: model:ir.ui.menu,name:cooperator.menu_move_out_invoice_type
idem

2022-09-05 14:56 UTC, robinkeunen commented
Discussed with @victor-champonnois : the safer way to do this would be to start from scratch `.pot` and `fr.po` files. Since all current customers have translations in place and new one will be on 14.0, we won't spend time on this (at least not without weblate).

2022-09-05 14:56 UTC, closed without merging

2022-09-19 08:09 UTC, huguesdk commented
follow-up: #372.