[IMP] add easy my coop flag on mail template
coopiteasy/vertical-cooperative pull request #37
Opened 2019-11-08 14:33 UTC by houssine78

2019-11-12 14:26 UTC, robinkeunen requested changes
Not sure but I guess you need to call super in your `init` methods.

2019-11-12 14:26 UTC, robinkeunen commented on easy_my_coop/__manifest__.py
> +    'version': '12.0.3.0.1',
waaaaw Houssine, keski te prend? <3

2019-11-12 14:26 UTC, robinkeunen commented on easy_my_coop/models/mail_template.py
> +    def init(self):
Faut pas faire un call à `super()`?

2019-11-12 14:26 UTC, robinkeunen commented on easy_my_coop_loan/models/mail_template.py
> +        for template_id in EMAIL_TEMPLATE_IDS:
même remarque

2019-11-12 14:26 UTC, robinkeunen commented on easy_my_coop_taxshelter_report/models/mail_template.py
> +        for template_id in EMAIL_TEMPLATE_IDS:
same

2019-11-13 10:32 UTC, remytms approved these changes

2019-11-13 10:32 UTC, remytms commented on easy_my_coop/__manifest__.py
> +    'version': '12.0.3.0.1',
Pourquoi `3.0.1` et pas `3.0.0` ? Mais c'est cool de mettre à jour les numéros de version. :)

2019-11-13 10:32 UTC, remytms commented on easy_my_coop_taxshelter_report/models/mail_template.py
> +        # TDE FIXME: should remove dfeault_type from context
Une coquille: `dfeault_type` -> `default_type`.

2019-11-13 13:58 UTC, houssine78 commented on easy_my_coop/__manifest__.py
> +    'version': '12.0.3.0.1',
@robinkeunen ahah
@remytms bonne question, il me semble que l'OCA commence toujours à x.0.1

2019-11-13 13:58 UTC, houssine78 commented on easy_my_coop/models/mail_template.py
> +    def init(self):
yep !

2019-11-22 14:32 UTC, robinkeunen commented
@houssine78 J'ai rebasé `coopiteasy/12.0-flag-easymycoop-mail-template` sur 12.0-target. Recommence bien depuis cette branche (celle de coopiteasy) pour ne pas que nous devions pas rerésoudre les conflits plus tard.

```bash
git checkout 12.0-flag-easymycoop-mail-template
git reset coopiteasy/12.0-flag-easymycoop-mail-template --hard
```

Je suggère aussi de laisser @remytms ou moi merger cette branche pour s'assurer qu'on ne merge pas dans 12.0 tout 12.0-target. (cf merge commits)

2019-11-25 17:26 UTC, remytms commented
@houssine78 @robinkeunen Pour cette PR comme pour `12.0-backend-configuration-structure` sur `investor-wallet-platform`, je dois savoir si tout est propre chez Houssine avant de faire une réécritured l'historique.

Donc pour l'instant, je ne la met pas en test. J'attend d'avoir le feu vert de Houssine.

2019-11-28 13:14 UTC, merged